version: "3.7"
services:
  app:
    image: node:18.10.0
    container_name: a-frame-demo1
    working_dir: /usr/src
    tty: true
    ports: 
    - '3000:3000'
    volumes:
      - ./:/usr/src
    command: bash -c "npm install && npm install nodemon -g && nodemon src/index.js"
